# Site settings
title: Moodsic
name: Moodsic
email: your-email@domain.com
description: "Mood and Music."
baseurl: ""
url: "http://ixdiego.github.io/moodsic"

# Build settings
markdown: kramdown
permalink: pretty
